version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-cli-version: latest
          context: aws-dev
          create-repo: true
          dockerfile: Dockerfile
          executor: aws-ecr/default
          path: .
          push-image: true
          region: ap-south-1
          registry-id: ENV_REGISTRY_ID
          repo: circleci-ecr-demo-v1
          tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
